version: "3"
services:
  backend:
    image: document-image
    container_name: "backend"
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # This comes from .env
        WKHTMLTOX_LOC: ${WKHTMLTOX_LOC}
    volumes:
      # IRG writes generated PDFs to /output. Map that directory to the
      # ./docker_pdf_output host directory in order to be able to view
      # generated PDFs in the host file system.
      - ./docker_pdf_output:/output
    entrypoint:
      - gunicorn
      - --name DOC
      - --worker-class uvicorn.workers.UvicornWorker
      - --pythonpath ./backend
      - --conf ./backend/gunicorn.conf.py
      - document.entrypoints.app:app
    networks:
      - local-net
  frontend:
    image: document-ui-image
    container_name: "frontend"
    build:
      context: ./frontend
      dockerfile: Dockerfile

# Network bridge for communication between containers
networks:
  local-net:
    driver: bridge
