version: "3"
services:
  api:
    image: document-image
    container_name: "api"
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # This comes from .env
        WKHTMLTOX_LOC: ${WKHTMLTOX_LOC}
    volumes:
      - ./docker_pdf_output:/output
    entrypoint:
      # Configure the server for fastapi, i.e., uvicorn
      - uvicorn
      - --host=0.0.0.0
      - --port=80
      - --reload
      - document.entrypoints.app:app
    networks:
      - local-net
    ports:
      - "5005:80"

# Network bridge for communication between containers
networks:
  local-net:
    driver: bridge
