version: "3"
services:
  api:
    image: document-image
    container_name: "api"
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # This comes from .env
        WKHTMLTOX_LOC: ${WKHTMLTOX_LOC}
    volumes:
      # FIXME Test if all is well without the next two mapped volumes
      # src and test. I don't think they are needed anymore.
      # Regardless, the Docker structure will undergoe a radical
      # change in a future update.
      - ./src:/src
      - ./tests:/tests
      - ./docker_pdf_output:/output
      #       IRG container writes logs rotated logs to its /logs directory.
      #       Map that directory to the ./logs directory on host so that we
      #       can access the logs for analysis.
      - ./logs:/logs
    entrypoint:
      # Configure the server for fastapi, i.e., uvicorn
      - uvicorn
      - --host=0.0.0.0
      - --port=80
      - --reload
      - document.entrypoints.app:app
    networks:
      - local-net
    ports:
      - "5005:80"

# Network bridge for communication between containers
networks:
  local-net:
    driver: bridge
