version: "2"
services:
  api:
    image: document-image
    container_name: "api"
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PANDOC_LOC: ${PANDOC_LOC}
        WKHTMLTOX_LOC: ${WKHTMLTOX_LOC}
    environment:
      - RESOURCE_ASSETS_DIR=/working/temp
      - DOCUMENT_OUTPUT_DIR=/working/temp
      - TRANSLATIONS_JSON_LOCATION=http://bibleineverylanguage.org/wp-content/themes/bb-theme-child/data/translations.json
      - LOGGING_CONFIG=src/document/logging_config.yaml
      - TEX_FORMAT_FILEPATH=tex/format.tex
      - TEX_TEMPLATE_FILEPATH=tex/template.tex
      - FASTAPI_HOST=0.0.0.0
      - FASTAPI_PORT=5005
      # - PYTHONDONTWRITEBYTECODE=1 # Incompatible with optimization in production.
      # - PYTHONUNBUFFERED=1  # Not sure we want this.
      # - PYTHONOPTIMIZE=1 # In particular, turn off icontract checks for production.
      # These emails are just for testing
      - FROM_EMAIL=foo@example.com
      - TO_EMAIL=foo@exmaple.com
      - IN_CONTAINER=1
      - ENABLE_ASSET_CACHING=1
    volumes:
      - ./src:/src
      - ./tests:/tests
      - ./docker_pdf_output:/output
    entrypoint:
      - uvicorn
      - --host=0.0.0.0
      - --port=80
      - --reload
      - document.entrypoints.app:app
    networks:
      - local-net
    ports:
      - "5005:80"

# Network bridge for communication between containers
networks:
  local-net:
    driver: bridge
