services:
  redis:
    image: redis:latest
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    restart: unless-stopped
  api:
    image: wycliffeassociates/doc:${IMAGE_TAG}
    env_file:
      - .env
    environment:
      TRANSLATIONS_JSON_LOCATION: ${TRANSLATIONS_JSON_LOCATION}
      BACKEND_CORS_ORIGINS: ${BACKEND_CORS_ORIGINS}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL:-redis://redis:6379/0}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND:-redis://redis:6379/0}
      FROM_EMAIL_ADDRESS: ${FROM_EMAIL_ADDRESS}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SEND_EMAIL: ${SEND_EMAIL}
    ports:
      - ${API_HOST_PORT:-5005}:5005
    command: gunicorn --name document:entrypoints:app --worker-class uvicorn.workers.UvicornWorker --pythonpath /app/backend --conf /app/backend/gunicorn.conf.py document.entrypoints.app:app
    volumes:
      - shared:/app/document_output
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5005/health/status"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    restart: unless-stopped
  worker:
    image: wycliffeassociates/doc:${IMAGE_TAG}
    command: celery --app=document.domain.worker.app worker --hostname=worker@%h --loglevel=DEBUG -E
    environment:
      CELERY_BROKER_URL: ${CELERY_BROKER_URL:-redis://redis:6379/0}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND:-redis://redis:6379/0}
      FROM_EMAIL_ADDRESS: ${FROM_EMAIL_ADDRESS}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SEND_EMAIL: ${SEND_EMAIL}
    volumes:
      - shared:/app/document_output
    depends_on:
      api:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: celery -A document.domain.worker.app inspect ping
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 15s

    restart: unless-stopped
  celery-dashboard:
    image: mher/flower
    environment:
      CELERY_BROKER_URL: ${CELERY_BROKER_URL:-redis://redis:6379/0}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND:-redis://redis:6379/0}
      FLOWER_PORT: 5555
    ports:
      - ${CELERY_DASHBOARD_HOST_PORT:-5555}:5555
    depends_on:
      redis:
        condition: service_healthy
      worker:
        condition: service_healthy
    restart: unless-stopped
  fileserver:
    build: ./web
    ports:
      - ${FILESERVER_HOST_PORT:-8089}:80
    volumes:
      - shared:/srv/content
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 5s
      timeout: 5s
      retries: 10
  frontend:
    image: wycliffeassociates/doc-ui:${IMAGE_TAG}
    environment:
      PUBLIC_BACKEND_API_URL: ${PUBLIC_BACKEND_API_URL:-http://localhost:5005}
      PUBLIC_FILE_SERVER_URL: ${PUBLIC_FILE_SERVER_URL:-http://localhost:8089}
      PUBLIC_LOGROCKET_ID: ${PUBLIC_LOGROCKET_ID:-ct7zyg/interleaved-resource-generator}
    ports:
      - ${FRONTEND_HOST_PORT:-80}:80
    depends_on:
      api:
        condition: service_healthy
      worker:
        condition: service_healthy
      fileserver:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  shared:
