version: "3"
services:
  backend:
    container_name: backend
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # These come from .env
        WKHTMLTOX_LOC: ${WKHTMLTOX_LOC}
        RUN_TESTS: ${RUN_TESTS}
        PORT: ${PORT}
        DOCUMENT_OUTPUT_DIR: ${DOCUMENT_OUTPUT_DIR}
    # volumes:
    #   # Writes generated PDFs to the value of DOCUMENT_OUTPUT_DIR which we map to
    #   # ./docker_pdf_output host directory in order to be able to view
    #   # generated PDFs in the host file system.
    #   - ./docker_pdf_output:${DOCUMENT_OUTPUT_DIR}
    ports:
      - 5005:5005
    networks:
      - local-net
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    networks:
      - local-net
    depends_on:
      - backend

# Network bridge for communication between containers
networks:
  local-net:
    driver: bridge
