version: "3"
services:
  api:
    image: wycliffeassociates/doc:${IMAGE_TAG}
    env_file:
      - .env
    environment:
      FROM_EMAIL_ADDRESS: ${FROM_EMAIL_ADDRESS}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      TO_EMAIL_ADDRESS: ${TO_EMAIL_ADDRESS}
      SMTP_HOST: ${SMTP_HOST}
      SEND_EMAIL: ${SEND_EMAIL}
      TRANSLATIONS_JSON_LOCATION: ${TRANSLATIONS_JSON_LOCATION}
      BACKEND_CORS_ORIGINS: ${BACKEND_CORS_ORIGINS}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL:-redis://redis:6379/0}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND:-redis://redis:6379/0}
    ports:
      - 5005:5005
    command: gunicorn --name document:entrypoints:app --worker-class uvicorn.workers.UvicornWorker --pythonpath /app/backend --conf /app/backend/gunicorn.conf.py document.entrypoints.app:app
    volumes:
      - shared:/app/document_output
    restart: unless-stopped
    depends_on:
      - redis
  worker:
    image: wycliffeassociates/doc:${IMAGE_TAG}
    command: celery --app=document.domain.worker.app worker --hostname=worker@%h --loglevel=DEBUG -E
    environment:
      CELERY_BROKER_URL: ${CELERY_BROKER_URL:-redis://redis:6379/0}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND:-redis://redis:6379/0}
    volumes:
      - shared:/app/document_output
    depends_on:
      - api
      - redis
    restart: unless-stopped
  redis:
    image: redis:latest
  celery-dashboad:
    image: mher/flower
    environment:
      CELERY_BROKER_URL: ${CELERY_BROKER_URL:-redis://redis:6379/0}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND:-redis://redis:6379/0}
      FLOWER_PORT: 5555
    ports:
      - 5555:5555
    depends_on:
      - redis
      - worker
  fileserver:
    build: ./web
    ports:
      - 8089:80
    volumes:
      - shared:/srv/content
    restart: unless-stopped
  frontend:
    image: wycliffeassociates/doc-ui:${IMAGE_TAG}
    environment:
      BACKEND_API_URL: ${BACKEND_API_URL:-http://localhost:5005}
      FILE_SERVER_URL: ${FILE_SERVER_URL:-http://localhost:8089}
    ports:
      - 8001:80
    depends_on:
      - api
    restart: unless-stopped

volumes:
  shared:
