version: "3"
services:
  api:
    image: wycliffeassociates/doc:${IMAGE_TAG}
    env_file:
      - .env
    environment:
      FROM_EMAIL_ADDRESS: ${FROM_EMAIL_ADDRESS}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      TO_EMAIL_ADDRESS: ${TO_EMAIL_ADDRESS}
      SMTP_HOST: ${SMTP_HOST}
      SEND_EMAIL: ${SEND_EMAIL}
    ports:
      - "5005:80"
    volumes:
      - docker_pdf_output:/output
  web:
    build: ./web
    ports:
      - "8089:80"
    volumes:
      - docker_pdf_output:/srv/content

volumes:
  docker_pdf_output:
