services:
  frontend:
    # use nginx as a mock frontend since the frontend isn't built or used at this stage
    image: nginx:alpine

  test-runner:
    image: wycliffeassociates/doc:${IMAGE_TAG}
    depends_on:
      api:
        condition: service_healthy
      worker:
        condition: service_healthy
      fileserver:
        condition: service_healthy
      celery-dashboard:
        condition: service_started

    entrypoint: pytest
    command: [
        "-vv",
        "-m",
        # "all",
        # "randomized",
        "not all and not randomized and not english_randomized",
        "-n",
        "auto",
        "/app/tests/unit",
        "/app/tests/e2e",
      ]
    environment:
      PUBLIC_BACKEND_API_URL: ${PUBLIC_BACKEND_API_URL:-http://localhost:5005}
      PUBLIC_FILE_SERVER_URL: ${PUBLIC_FILE_SERVER_URL:-http://localhost:8089}
      PUBLIC_LOGROCKET_ID: ${PUBLIC_LOGROCKET_ID:-ct7zyg/bible-in-every-language}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL:-redis://redis:6379/0}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND:-redis://redis:6379/0}
      FROM_EMAIL_ADDRESS: ${FROM_EMAIL_ADDRESS:-foo@example.com}
      SMTP_PASSWORD: ${SMTP_PASSWORD:-fakepass}
      SMTP_HOST: ${SMTP_HOST:-smtp.example.com}
      SMTP_PORT: ${SMTP_PORT:-111}
      SEND_EMAIL: ${SEND_EMAIL:-False}
    volumes:
      - shared:/app/document_output

volumes:
  shared:
