version: "2"
services:
  api:
    image: document-image
    container_name: "api"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # FIXME Next three have no values
      - IRG_WORKING_DIR=/working/temp
      - IRG_OUTPUT_DIR=/working/temp
      - IRG_CS_USER_URL=https://content.bibletranslationtools.org/WycliffeAssociates
      - TRANSLATIONS_JSON_LOCATION=http://bibleineverylanguage.org/wp-content/themes/bb-theme-child/data/translations.json
      - LOGGING_CONFIG=document/logging_config.yaml
      # - TN_ADDITIONAL_PARMS
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - IN_CONTAINER=1
    volumes:
      - ./src:/src
      - ./tests:/tests
    entrypoint:
      - uvicorn
      - --host=0.0.0.0
      - --port=80
      - --reload
      - document.entrypoints.app:app
    networks:
      - local-net
    ports:
      - "5005:80"

# Network bridge for communication between containers
networks:
  local-net:
    driver: bridge
