version: "3"
services:
  api:
    image: wycliffeassociates/doc:${IMAGE_TAG}
    environment:
      FROM_EMAIL_ADDRESS: ${FROM_EMAIL_ADDRESS}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      TO_EMAIL_ADDRESS: ${TO_EMAIL_ADDRESS}
      SMTP_HOST: ${SMTP_HOST}
      SEND_EMAIL: ${SEND_EMAIL}
      TRANSLATIONS_JSON_LOCATION: ${TRANSLATIONS_JSON_LOCATION}
      BACKEND_CORS_ORIGINS: ${BACKEND_CORS_ORIGINS}
    ports:
      - 5005:5005
    volumes:
      - ./docker_document_output:/document_output
    restart: unless-stopped
  fileserver:
    build: ./web
    ports:
      - 8089:80
    volumes:
      - docker_document_output:/srv/content
    restart: unless-stopped
  frontend:
    image: wycliffeassociates/doc-ui:${IMAGE_TAG}
    environment:
      VITE_BACKEND_API_URL: ${VITE_BACKEND_API_URL}
    ports:
      - 8001:80
    depends_on:
      - api
    restart: unless-stopped

volumes:
  docker_document_output:
