import { expect, test } from '@playwright/test'

test('rmp galatians', async ({ page }) => {
  await page.goto('http://localhost:8001/')
  await page.getByRole('button', { name: 'Heart' }).click()
  await page.getByPlaceholder('Search Heart Languages').click()
  await page.getByPlaceholder('Search Heart Languages').fill('rmp')
  await page.getByText('Rempi').click()
  await page.getByRole('button', { name: 'Next' }).click()
  await expect(page.getByRole('main')).toContainText('Galasians', { timeout: 10000 })
  await page.getByLabel('Titus ti').check()
  await page.getByRole('button', { name: 'Next' }).click()
  await page.getByText('Regular').click()
  await page.getByRole('button', { name: 'Next' }).click()
  await page.getByText('Docx').click()
  await page.getByText('Interleave content by book').click()
  await page.getByRole('button', { name: 'Generate File' }).click()
})

test('include tn book and chapter intros is checked by default for this case', async ({ page }) => {
  await page.goto('http://localhost:8001/')
  await page.getByLabel('Français (French) fr').check()
  await page.getByRole('button', { name: 'Next' }).click()
  await page.getByText('Galates').click()
  await page.getByRole('button', { name: 'Next' }).click()
  await page.getByText('French Louis Segond 1910 Bible').click()
  await page.getByText('Unlocked Literal Bible').click()
  await page.getByText('Translation Notes').click()
  await page.getByText('Translation Words').click()
  await page.getByRole('button', { name: 'Next' }).click()
  await page.getByRole('button', { name: '▶ Show Optional Settings' }).click()
  // await expect(page.locator('#use-two-column-layout-for-tn')).not.toBeChecked()
  await expect(page.locator('#show-tn-book-intro')).toBeChecked()
  await expect(page.locator('#show-tn-chapter-intro')).toBeChecked()
})
