import { expect, test } from '@playwright/test'

test('visibility of optional settings based on resources chosen', async ({ page }) => {
  await page.goto('http://localhost:8001/')
  await page.getByText('Français (French)').click()
  await page.getByRole('button', { name: 'Next' }).click()
  await page.getByText('Select all').click()
  await page.getByRole('button', { name: 'Next' }).click()
  await page.getByText('Select all').click()
  await page.getByLabel('French Louis Segond 1910').uncheck()
  await page.getByLabel('Translation Words tw').uncheck()
  await page.getByRole('button', { name: 'Next' }).click()
  // await page.getByRole('radio', { name: 'PDF' }).click()
  await page.getByRole('button', { name: '▶ Show Optional Settings' }).click()
  await expect(page.getByRole('main')).toContainText(
    "Use chapter labels, e.g., 'Chapter 1' instead of '1'"
  )
  // await expect(page.getByRole('main')).toContainText('Translation notes layout:')
  // await expect(page.getByRole('main')).toContainText('Translation questions layout:')
  await page.getByRole('button', { name: 'Edit' }).nth(2).click()
  await page.getByText('Translation Questions', { exact: true }).click()
  await page.getByRole('button', { name: 'Next' }).click()
  await page.getByRole('button', { name: '▶ Show Optional Settings' }).click()
  // await expect(page.getByRole('main')).not.toContainText('Translation questions layout:')
  await page.getByRole('button', { name: 'Edit' }).nth(2).click()
  await page.getByLabel('Translation Notes tn').uncheck()
  await page.getByRole('button', { name: 'Next' }).click()
  await page.getByRole('button', { name: '▶ Show Optional Settings' }).click()
  // await expect(page.getByRole('main')).not.toContainText('Translation notes layout:')
  await expect(page.getByRole('main')).toContainText(
    "Use chapter labels, e.g., 'Chapter 1' instead of '1'"
  )
  await page.getByRole('button', { name: 'Edit' }).nth(2).click()
  await page.getByText('Translation Notes').click()
  await page.getByLabel('Unlocked Literal Bible ulb').uncheck()
  await page.getByRole('button', { name: 'Next' }).click()
  await page.getByRole('button', { name: '▶ Show Optional Settings' }).click()
  // await expect(page.getByRole('main')).toContainText('Translation notes layout:')
  await expect(page.getByRole('main')).not.toContainText(
    "Use chapter labels, e.g., 'Chapter 1' instead of '1'"
  )
})

test('burmese', async ({ page }) => {
  await page.goto('http://localhost:8001/')
  await page.getByPlaceholder('Search Gateway Languages').click()
  await page.getByPlaceholder('Search Gateway Languages').fill('my')
  await page.getByText('ျမန္မာစာ (Burmese)').click()
  await page.getByRole('button', { name: 'Next' }).click()
  await page.getByText('ရှင်မဿဲခရစ်ဝင်။').click()
  await page.getByText('ရှင်မာကုခရစ်ဝင်။').click()
  await page.getByText('ရှင်လုကာခရစ်ဝင်။').click()
  await page.getByRole('button', { name: 'Next' }).click()
  await page.getByText('Translation Notes').click()
  await page.getByLabel('Translation Notes tn').uncheck()
  await expect(page.locator('body')).toContainText('Translation Notes')
  await expect(page.locator('body')).toContainText('Translation Questions')
  await expect(page.locator('body')).toContainText('Translation Words')
  await expect(page.locator('body')).toContainText('Unlocked Literal Bible')
  await page.getByLabel('Select all').check()
  await page.getByRole('button', { name: 'Next' }).click()
  // await page.getByRole('radio', { name: 'PDF' }).click()
  // await page.getByText('Use PrinceXml to produce the').click()
  await page.getByRole('button', { name: 'Generate File' }).click()
})
