import { test, expect } from '@playwright/test'

test('add passages', async ({ page }) => {
  await page.goto('http://localhost:8001/passages')
  await page.getByText('Español Latin America (Latin').click()
  await page.getByRole('button', { name: 'Next' }).click()
  const passagesSection = page.locator('#passages-basket')
  await page.getByLabel('Bible Book').selectOption('jos')
  await expect(page.getByLabel('Chapter')).toBeEnabled({ timeout: 10000 })
  await expect(page.getByLabel('Chapter').locator('option[value="7"]')).toBeAttached()
  await page.getByLabel('Chapter').selectOption('7')
  await page.getByPlaceholder('e.g., 1,2,5-').fill('1-10')
  await page.getByRole('button', { name: 'Add Passage' }).click()
  await page.getByLabel('Bible Book').selectOption('est')
  await expect(page.getByLabel('Chapter').locator('option[value="7"]')).toBeAttached()
  await page.getByLabel('Chapter').selectOption('7')
  await page.getByPlaceholder('e.g., 1,2,5-').fill('3,12')
  await page.getByRole('button', { name: 'Add Passage' }).click()
  await page.getByLabel('Bible Book').selectOption('1th')
  await expect(page.getByLabel('Chapter').locator('option[value="4"]')).toBeAttached()
  await page.getByLabel('Chapter').selectOption('4')
  await page.getByPlaceholder('e.g., 1,2,5-').fill('1,5-8,11')
  await page.getByRole('button', { name: 'Add Passage' }).click()
  await expect(passagesSection).toContainText('Josué 7:1-10 (es-419)')
  await expect(passagesSection).toContainText('Ester 7:3,12 (es-419)')
  await expect(passagesSection).toContainText('1 Tesalonicenses 4:1,5-8,11 (es-419)')
  await page.getByRole('button', { name: 'Next' }).click()
  await page.getByRole('button', { name: 'Generate File' }).click()
})

test('select gateway tab after first selecting heart language and hitting next', async ({
  page
}) => {
  await page.goto('http://localhost:8001/passages')
  await page.getByRole('button', { name: 'Heart' }).click()
  await page.getByText('Abure').click()
  await page.getByRole('button', { name: 'Next' }).click()
  await page.getByRole('link', { name: 'Language' }).click()
  await page.getByText('Cebuano').click()
  await page.getByRole('button', { name: 'Next' }).click()
  await page.waitForTimeout(20000)
  await page.getByText("Add NT Survey Reviewers'").click()
  await page.waitForTimeout(30000)
  await expect(page.getByTestId('shown-passages')).toContainText('(ceb)', { timeout: 120000 })
  const passagesSection = page.getByTestId('shown-passages')
  const text = await passagesSection.innerText()
  // console.log('DEBUG TEXT:')
  // console.log(JSON.stringify(text)) // helpful for spotting hidden chars
  expect(text).toMatch(/Mat+t?hieu.*2:1-12.*\(abu\)/i)
  expect(text).toMatch(/Mateo.*2:1-12.*\(ceb\)/i)
})

test('passages checkboxes', async ({ page }) => {
  await page.goto('http://localhost:8001/passages')
  await page.getByText('English').click()
  await page.getByRole('button', { name: 'Next' }).click()
  await page.getByLabel('Add OT Survey RG1 Passages').check()
  await expect(page.locator('body')).toContainText('Genesis 1:1-2:3', { timeout: 32_000 })
  await page.getByLabel('Add OT Survey RG1 Passages').uncheck()
  await expect(page.locator('body')).not.toContainText('Genesis 1:1-2:3', { timeout: 32_000 })
  await page.getByLabel('Add OT Survey RG2 Passages').check()
  await expect(page.locator('body')).toContainText('Joshua 1:1-9', { timeout: 32_000 })
  await page.getByLabel('Add OT Survey RG2 Passages').uncheck()
  await expect(page.locator('body')).not.toContainText('Joshua 1:1-9', { timeout: 32_000 })
  await page.getByLabel('Add OT Survey RG3 Passages').check()
  await expect(page.locator('body')).toContainText('Job 1:6-22')
  await page.getByLabel('Add OT Survey RG3 Passages').uncheck()
  await expect(page.locator('body')).not.toContainText('Job 1:6-22')
  await page.getByLabel('Add OT Survey RG4 Passages').check()
  await expect(page.locator('body')).toContainText('Isaiah 1:1-9', { timeout: 32_000 })
  await page.getByLabel('Add OT Survey RG4 Passages').uncheck()
  await expect(page.locator('body')).not.toContainText('Isaiah 1:1-9', { timeout: 32_000 })
  await page.getByLabel("Add NT Survey Reviewers'").check()
  await expect(page.locator('body')).toContainText('Matthew 2:1-12', { timeout: 32_000 })
  await page.getByLabel("Add NT Survey Reviewers'").uncheck()
  await expect(page.locator('body')).not.toContainText('Matthew 2:1-12', { timeout: 32_000 })
  // await page.getByLabel('Add STET Passages').check()
  // await expect(page.locator('body')).toContainText('Matthew 1:1', { timeout: 32_000 })
  // await page.getByLabel('Add STET Passages').uncheck()
  // await expect(page.locator('body')).not.toContainText('Matthew 1:1', { timeout: 32_000 })
  await page.getByLabel("Add all OT Survey Reviewers' Guide (RG) Passages").check()
  await expect(page.locator('body')).toContainText('Genesis 1:1-2:3', { timeout: 32_000 })
  await page.getByLabel("Add all OT Survey Reviewers' Guide (RG) Passages").uncheck()
  await expect(page.locator('body')).not.toContainText('Genesis 1:1-2:3', { timeout: 32_000 })
  await page.getByLabel('Bible Book').selectOption('lev')
  await page.getByLabel('Chapter').selectOption('6')
  await page.getByPlaceholder('e.g., 1,2,5-').click()
  await page.getByPlaceholder('e.g., 1,2,5-').fill('1,2,5-7')
  await page.getByPlaceholder('e.g., 1,2,5-').press('Tab')
  await page.getByRole('button', { name: 'Add Passage' }).click()
  await expect(page.locator('body')).toContainText('Leviticus 6:1,2,5-7')
})
