import { test, expect } from '@playwright/test'

test('test', async ({ page }) => {
  await page.goto('http://localhost:8001/passages/language')
  await page.getByText('Español Latin America (Latin').click()
  await page.getByRole('button', { name: 'Next' }).click()
  await page.getByLabel('Bible Book').selectOption('jos')
  await page.getByLabel('Chapter').selectOption('7')
  await page.getByPlaceholder('e.g., 1,2,5-').click()
  await page.getByPlaceholder('e.g., 1,2,5-').fill('1-10')
  await page.getByRole('button', { name: 'Add Passage' }).click()
  await page.getByLabel('Bible Book').selectOption('est')
  await page.getByLabel('Chapter').selectOption('7')
  await page.getByPlaceholder('e.g., 1,2,5-').click()
  await page.getByPlaceholder('e.g., 1,2,5-').fill('3,12')
  await page.getByRole('button', { name: 'Add Passage' }).click()
  await page.getByLabel('Bible Book').selectOption('1th')
  await page.getByLabel('Chapter').selectOption('4')
  await page.getByPlaceholder('e.g., 1,2,5-').click()
  await page.getByPlaceholder('e.g., 1,2,5-').fill('1,5-8,11')
  await page.getByRole('button', { name: 'Add Passage' }).click()
  await page.getByRole('button', { name: 'Next' }).click()
  await page.getByRole('button', { name: 'Generate File' }).click()
})
