TRANSLATED_HEADER_PHRASES_TABLE: dict[str, str] = {
    "en": "Spiritual Terms Evaluation Tool (STET)",
    "ceb": "Kagamitan sa Pagrepaso sa Espirituhanong mga Termino (STET)",
    "es-419": "Herramienta de Evaluación de Términos Espirituales (STET)",
    "fr": "Évaluation des Termes Spirituels (STET)",
    "gu": "આધ્યાત્મિક શબ્દો મૂલ્યાંકન સાધન (STET)",
    "id": "Alat Evaluasi Istilah Spiritual (STET)",
    "pt-br": "Ferramenta de Avaliação de Termos Espirituais (STET)",
    "bg": "Инструмент за оценка на духовни термини (STET)",
    "ru": "Инструмент оценки духовных терминов (STET)",
    "sw": "Chombo cha Kutathmini Maneno ya Kiroho (STET)",
    "tl": "Kagamitan sa Pagsusuri ng mga Espiritwal na Salita (STET)",
    "tpi": "Tul bilong skelim ol spirit tok bilong buk trenslesen (STET)",
    "vi": "Công cụ Đánh giá Thuật ngữ Tâm linh (STET)",
}

TRANSLATED_FOOTER_PHRASES_TABLE: dict[str, str] = {
    "en": "Generated on",
    "ceb": "Gihimo noong",
    "es-419": "Generado el",
    "fr": "Généré le",
    "gu": "તૈયાર કરેલ તારીખ",
    "id": "Dibuat pada",
    "pt-br": "Gerado em",
    "bg": "Генерирано на",
    "ru": "Сформировано",
    "sw": "Imetolewa tarehe",
    "tl": "Nabuo noong",
    "tpi": "Wok i bin kamap long",
    "vi": "Được tạo vào",
}

LOCALIZED_DATE_FORMAT_STRINGS: dict[str, str] = {
    "en": "%m/%d/%Y %H:%M:%S",
    "ceb": "%d/%m/%Y %H:%M:%S",
    "es-419": "%d/%m/%Y %H:%M:%S",
    "fr": "%d/%m/%Y %H:%M:%S",
    "gu": "%d/%m/%Y %H:%M:%S",
    "id": "%d/%m/%Y %H:%M:%S",
    "pt-br": "%d/%m/%Y %H:%M:%S",
    "bg": "%d.%m.%Y %H:%M:%S",
    "ru": "%d.%m.%Y %H:%M:%S",
    "sw": "%d/%m/%Y %H:%M:%S",
    "tl": "%m/%d/%Y %H:%M:%S",
    "tpi": "%d/%m/%Y %H:%M:%S",
    "vi": "%d/%m/%Y %H:%M:%S",
}

TRANSLATED_TABLE_COLUMN_HEADERS = {
    "en": ("Source Reference", "Target Reference", "Status", "OK"),
    "ceb": ("Gikanang Reperensya", "Target nga Reperensya", "Posisyon", "OK"),
    "es-419": ("Fuente", "Idioma Materna", "Estado", "OK"),
    "fr": ("Référence de source", "Référence Cible", "Statut", "OK"),
    "gu": (
        "Препратка към изходния текст – текста на български",
        "Препратка към преведения текст – текста на цигански",
        "Текущо състояние",
        "OK",
    ),
    "id": ("Referensi Sumber", "Referensi Target", "Status", "OK"),
    "pt-br": ("Referência de Origem", "Referência de Destino", "Status", "OK"),
    "bg": (
        "Изходна препратка",
        "Целева препратка",
        "Статус",
        "OK",
    ),
    "ru": (
        "Ссылка на исходный текст",
        "Ссылка на переведенный текст",
        "статус",
        "Удовл",
    ),
    "sw": ("Marejeo Chanzo", "Marejeo Lengwa", "Hali", "OK"),
    "tl": ("Pinagmulang Sangguniun", "Lalagyang Sangguniun", "Katayuan", "OK"),
    "tpi": ("Narapela baibel ves", "Tokples ves", "Sek", "OK"),
    "vi": ("Tham chiếu nguồn", "Tham chiếu đích", "Trạng thái", "Đạt"),
}
