TRANSLATED_HEADER_PHRASES_TABLE: dict[str, str] = {
    "bg": "Инструмент за оценка  проверка на духовни термини (STET)",
    "ceb": "Kagamitan sa Pagsusi sa Espirituhanong mga Termino (STET)",
    "en": "Spiritual Terms Evaluation Tool (STET)",
    "es-419": "Herramienta de evaluación de términos espirituales (STET)",
    "fr": "Outil d’évaluation des termes spirituels (STET)",
    "gu": "આધ્યાત્મિક શબ્દો મૂલ્યાંકન સાધન (STET)",
    "id": "Alat Evaluasi Istilah Spiritual (STET)",
    "pt-br": "Ferramenta de avaliação de termos espirituais (STET)",
    "ru": "Инструмент оценки духовных терминов (STET)",
    "sw": "Chombo cha Kutathmini Istilahi za Kiroho (STET)",
    "tl": "Kagamitan sa Pagsusuri ng mga Espiritwal na Termino (STET)",
    "tpi": "Tul bilong skelim ol spirituel tok (STET)",
    "vi": "Công cụ Đánh giá Thuật ngữ Tâm linh (STET)",
}

TRANSLATED_FOOTER_PHRASES_TABLE: dict[str, str] = {
    "bg": "Генерирано на дата",
    "ceb": "Gihimo sa",
    "en": "Generated on",
    "es-419": "Generado el",
    "fr": "Généré le",
    "gu": "તૈયાર કરેલ તારીખ",
    "id": "Dibuat pada",
    "pt-br": "Gerado em",
    "ru": "Создано",
    "sw": "Imetolewa tarehe",
    "tl": "Nabuo noong",
    "tpi": "Wokim long",
    "vi": "Được tạo vào",
}

LOCALIZED_DATE_FORMAT_STRINGS: dict[str, str] = {
    "bg": "%d.%m.%Y %H:%M:%S",
    "ceb": "%d/%m/%Y %H:%M:%S",
    "en": "%m/%d/%Y %H:%M:%S",
    "es-419": "%d/%m/%Y %H:%M:%S",
    "fr": "%d/%m/%Y %H:%M:%S",
    "gu": "%d/%m/%Y %H:%M:%S",
    "id": "%d/%m/%Y %H:%M:%S",
    "pt-br": "%d/%m/%Y %H:%M:%S",
    "ru": "%d.%m.%Y %H:%M:%S",
    "sw": "%d/%m/%Y %H:%M:%S",
    "tl": "%d/%m/%Y %H:%M:%S",
    "tpi": "%d/%m/%Y %H:%M:%S",
    "vi": "%d/%m/%Y %H:%M:%S",
}

TRANSLATED_TABLE_COLUMN_HEADERS = {
    "bg": (
        "Препратка към изходния текст",
        "Препратка към целевия преведения текст",
        "Текущо състояние",
        "OK",
    ),
    "ceb": ("Gikanan nga Reperensya", "Target nga Reperensya", "Kahimtang", "OK"),
    "en": ("Source Reference", "Target Reference", "Status", "OK"),
    "es-419": ("Referencia de origen", "Referencia de destino", "Estado", "OK"),
    "fr": ("Référence source", "Référence cible", "Statut", "OK"),
    "gu": ("સ્ત્રોત લખાણનો સંદર્ભ", "લક્ષ્ય લખાણનો સંદર્ભ", "સ્થિતિ", "OK"),
    "id": ("Referensi Sumber", "Referensi Target", "Status", "OK"),
    "pt-br": ("Referência de Origem", "Referência de Destino", "Status", "OK"),
    "ru": (
        "Ссылка на исходный текст",
        "Ссылка на переведенный текст",
        "Статус",
        "ОК",
    ),
    "sw": ("Marejeo ya Chanzo", "Marejeo ya Lengwa", "Hali", "OK"),
    "tl": ("Sanggunian ng Pinagmulan", "Sanggunian ng Target", "Katayuan", "OK"),
    "tpi": ("Sos referens", "Taget referens", "Stetas", "OK"),
    "vi": ("Tham chiếu nguồn", "Tham chiếu đích", "Trạng thái", "OK"),
}
