name: Docker

on: [push, pull_request]

jobs:
  build-and-test-api:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: FranzDiebold/github-env-vars-action@v2

      - name: Build API image
        shell: bash
        run: docker build -t wycliffeassociates/doc:$GITHUB_SHA -t wycliffeassociates/doc:$GITHUB_REF_NAME -t wycliffeassociates/doc:latest .

      - name: Test API image
        shell: bash
        run: docker compose up -d && docker-compose run --rm --no-deps --entrypoint=pytest api -v -m "not randomized" -n auto /app/tests/unit /app/tests/e2e

  build-and-test-ui:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: FranzDiebold/github-env-vars-action@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 19

      - name: Build UI image
        shell: bash
        run: docker build -t wycliffeassociates/doc-ui:$GITHUB_SHA -t wycliffeassociates/doc-ui:$GITHUB_REF_NAME -t wycliffeassociates/doc-ui:latest ./frontend

      - name: Run API for UI
        shell: bash
        run: docker compose up -d

      - name: Install dependencies outside Docker for Playwright use
        shell: bash
        run: cd frontend && npm ci

      - name: Substitute frontend env var for Playwright
        shell: bash
        run: cd frontend && envsubst < playwright.config.ts | sponge playwright.config.ts

      - name: Install Playwright
        shell: bash
        run: npx playwright install --with-deps

      - name: Test UI image
        shell: bash
        run: cd frontend && npx playwright test

  publish:
    runs-on: ubuntu-20.04
    if: github.event_name == 'push'
    needs: [build-and-test-api, build-and-test-ui]

    steps:
      - uses: actions/checkout@v2
      - uses: FranzDiebold/github-env-vars-action@v2

      - name: Build API image
        shell: bash
        run: docker build -t wycliffeassociates/doc:$GITHUB_SHA -t wycliffeassociates/doc:$GITHUB_REF_NAME -t wycliffeassociates/doc:latest .

      - name: Build UI image
        shell: bash
        run: docker build -t wycliffeassociates/doc-ui:$GITHUB_SHA -t wycliffeassociates/doc-ui:$GITHUB_REF_NAME -t wycliffeassociates/doc-ui:latest ./frontend

      - name: Log into registry
        shell: bash
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_TOKEN }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USER }}
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Docker push api image
        run: |
          docker push -a wycliffeassociates/doc

      - name: Docker push ui image
        run: |
          docker push -a wycliffeassociates/doc-ui
