name: Docker

on: [push, pull_request]

jobs:
  #build and publish image
  test-and-conditional-publish:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: FranzDiebold/github-env-vars-action@v2
      
      - name: Set DOC docker tags
        run: |
          echo "DOC_TAG_SHA=wycliffeassociates/doc:$GITHUB_SHA" >> $GITHUB_ENV && \
          echo "DOC_TAG_BRANCH=wycliffeassociates/doc:$CI_REF_NAME_SLUG" >> $GITHUB_ENV && \
          echo "DOC_TAG_LATEST=wycliffeassociates/doc:latest" >> $GITHUB_ENV
      - name: Set DOC-UI docker tags
        run: |
          echo "DOC_UI_TAG_SHA=wycliffeassociates/doc:$GITHUB_SHA" >> $GITHUB_ENV && \
          echo "DOC_UI_TAG_BRANCH=wycliffeassociates/doc:$CI_REF_NAME_SLUG" >> $GITHUB_ENV && \
          echo "DOC_UI_TAG_LATEST=wycliffeassociates/doc:latest" >> $GITHUB_ENV
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      -
        name: Build and conditional push API image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ contains(fromJson('["push"]'), github.event_name) }}
          build-args: RUN_TESTS=true
          tags: |
            ${{ env.DOC_TAG_SHA }}
            ${{ env.DOC_TAG_BRANCH }}
            ${{ env.DOC_TAG_LATEST }}
      -
        name: Build and conditional push UI image
        uses: docker/build-push-action@v3
        with:
          context: ./frontend
          push: ${{ contains(fromJson('["push"]'), github.event_name) }}
          tags: |
            ${{ env.DOC_UI_TAG_SHA }}
            ${{ env.DOC_UI_TAG_BRANCH }}
            ${{ env.DOC_UI_TAG_LATEST }}
